apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: yzub5lvz4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yzub5lvz4-go 
  name: yzub5lvz4-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: yzub5lvz4-go
    weight: 100 
